apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petid-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://admin.petid.app,https://petid.app"
spec:
  tls:
    - hosts:
        - api.petid.app
        - admin.petid.app
      secretName: petid-tls
  rules:
    - host: api.petid.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petid-api
                port:
                  number: 3000
    - host: admin.petid.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petid-web
                port:
                  number: 3001
