export const Colors = {
  light: {
    primary:    '#0A84FF',
    primaryLight: '#60a5fa',
    background: '#F2F2F7',
    surface:    '#FFFFFF',
    surfaceSecondary: '#F2F2F7',
    surfaceTertiary: '#E5E5EA',
    text:       '#000000',
    textSecondary: '#6C6C70',
    textTertiary: '#AEAEB2',
    border:     '#D1D1D6',
    borderLight: '#E5E5EA',
    success:    '#34C759',
    warning:    '#FF9500',
    danger:     '#FF3B30',
    info:       '#0A84FF',
    tabBar:     '#FFFFFF',
    tabBarBorder: '#E5E5EA',
    separator:  '#E5E5EA',
    placeholder: '#AEAEB2',
    overlay:    'rgba(0,0,0,0.4)',
    skeleton:   '#E5E5EA',
    skeletonHighlight: '#F5F5F5',
  },
  dark: {
    primary:    '#0A84FF',
    primaryLight: '#1D4ED8',
    background: '#000000',
    surface:    '#1C1C1E',
    surfaceSecondary: '#2C2C2E',
    surfaceTertiary: '#3A3A3C',
    text:       '#FFFFFF',
    textSecondary: '#EBEBF5CC',
    textTertiary: '#EBEBF599',
    border:     '#38383A',
    borderLight: '#2C2C2E',
    success:    '#30D158',
    warning:    '#FF9F0A',
    danger:     '#FF453A',
    info:       '#0A84FF',
    tabBar:     '#1C1C1E',
    tabBarBorder: '#38383A',
    separator:  '#38383A',
    placeholder: '#636366',
    overlay:    'rgba(0,0,0,0.6)',
    skeleton:   '#2C2C2E',
    skeletonHighlight: '#3A3A3C',
  },
} as const;

export type ColorScheme = keyof typeof Colors;
export type ThemeColors = typeof Colors.light;
